### ISSUE TITLE
add to asset library

### ISSUE THREAD

**Issue by ilo-3a29** [TeddyDD/gterm#2]
would it be possible to add this to the godot asset library?

**Comment by TeddyDD** [comment]
Sure, as soon as asset library will be officially released.

**Comment by ilo-3a29** [comment]
It is officially released, with the latest engine update.

**Comment by TeddyDD** [comment]
I thought its in beta or something. Its not even mentioned in Godot website (there is something in blog). I'll look into this and I close this issue when I add gterm to asset library.

Edit: 

> Thanks to the development work done by Alket Rexhepi and Bojidar Marinov, this frontend will **soon reach the alpha status and be announced officially**, so that all community members can start submitting assets to the library.

Anyway, it seems that I'll have to change directory structure first to match Asset library style and attach it as zip to release tag.
**Todo**
- [ ] double check if gterm works fine as plugin
- [ ] attach zip to newest tag
- [ ] record short showcase video and upload it to yt
- [ ] uploat to asset library

**Comment by TeddyDD** [comment]
Asset Library is now in beta https://godotengine.org/article/asset-library-web-frontend-reaches-beta I have to look into this issue again :)
